[database]
host = "192.168.75.128"
user = "aidata"
password = "nexus!234"
database = "aidata"
port = 3306

[server]
port = 5000
threshold = 0.35
top_k = 3
theme = "whitegrayb"
enable_duck_animation = false
jwt_secret = "nexus!@#$%^&*{}<>"

[files]
model = "model/randomforest_model.pkl"
templates = "model/reply_templates_50.json"

[feedback]
max_length = 1000